### PR TITLE
PR: make print() and __repr__() return the same string for Graph objects

### PR DESCRIPTION
**Pull request by Abelarm**
Issue: #4 

I wrote a custom_repr function that takes as input the node and an int that represent the depth of that node for printing with the right indentation.

the __repr__ function calls this custom function passing 0 as depth

I know you posted that link, but with repr you can't have parameters instead i needed one

### CODE REVIEW

**Comment by Abelarm** [comment]
The problem on the build is due to this:

screen shot 2018-10-17 at 18 47 25

I don't know how to solve 👎

**Comment by capsulecorplab** [comment]
Hey @Abelarm, thanks for the PR!

I'm not seeing that error on my end; I'm guessing it's a mypy thing. Though, looking at the build logs, it looks like it's just a linting error that's triggering a travis fail:

```
/home/saiyaman/gitrepos/cloned/mindgraph/mindgraph/graph.py:63:80: E501 line too long (90 > 79 characters)
                    map(functools.partial(node.custom_repr, depth=depth+1), node.threads))
                                                                               ^
/home/saiyaman/gitrepos/cloned/mindgraph/mindgraph/graph.py:66:80: E501 line too long (92 > 79 characters)
                    map(functools.partial(node.custom_repr, depth=depth + 1), node.threads))
                                                                               ^
/home/saiyaman/gitrepos/cloned/mindgraph/mindgraph/graph.py:68:80: E501 line too long (87 > 79 characters)
                return "    "*(depth-1) + "- {}".format(node.name) + ":\n" + '\n'.join(
                                                                               ^
/home/saiyaman/gitrepos/cloned/mindgraph/mindgraph/graph.py:69:80: E501 line too long (92 > 79 characters)
                    map(functools.partial(node.custom_repr, depth=depth + 1), node.threads))
                                                                               ^
```

I cloned and tested your branch on my local machine and it seems to work just fine! Let me know if you want to try and fix it on your end. Otherwise, I'll just change the base branch for this PR, delint it in a separate branch, then merge into master later.

**Comment by Abelarm** [comment]
yeah you were right wasn't about mypy as i thought
was the ******* linting

**Comment by Abelarm** [comment]
all checks passed 🥇

**Comment by capsulecorplab** [comment]
Awesome!

**Pull request merged**
